---
title: On statistical reporting in biomedical journals
author: ''
date: '2018-04-25'
slug: on-statistical-reporting-in-biomedical-journals
categories: [guidelines, reporting]
tags: [guidelines, reporting ]
output: 
  bookdown::html_document2: 
    fig_caption: yes
header:
  caption: ''
  image: ''
bibliography: biblio.bib
link-citations: yes
draft: true
---

Poor quality statistical reporting in the biomedical literature is not uncommon. Here is another example by @cirio2016effects. The study itself is well planed, executed and reported.
The aim was to assess whether heated and humidified high flow gases delivered through nasal cannula (HFNC) improve exercise performance in severe chronic obstructive pulmonary disease (COPD) patients. It all started when I show their Fig.1. Here is my attempt to reproduce it 

```{r figs, echo = F, fig.cap = "Effect of the HFNC on exercise capacity compared to a control condition. Tlim = exercise duration."}
x <- c(300, 320, 327, 415, 420, 428, 433, 480, 495, 548, 550, 555)*0.965
y <- (c(365, 384, 380, 480, 470, 540, 540, 550, 540, 610, 560, 999) + 12)*0.965
id <- rep(1:12)
time <- c(rep("Control test", 12), rep("NFNC test", 12))

data <- data.frame(id = c(id, id), value = c(x, y), time = time)

library("ggplot2")

ggplot(data = data, aes(x = time, y = value, group = id)) + 
   geom_line() + 
   geom_point(size = 3) + 
   ylim(0, 1000) + 
   ylab("Tlim, sec") +
   xlab("") + 
   geom_point(aes(y = (999 + 12)*0.965, x = "NFNC test"), col = "red", size = 3) + 
   geom_point(aes(y = 555*0.965, x = "Control test"), col = "red", size = 3)
```

In total there are 12 patients tested twice; once under the control test and once under the NFNC test. The outcome of interest is the endurance time (Tlim; y axis). This is practically how long each test lasted. The authors hypothesized that HFNC would improve exercise performance. This was the case since Tlim increased for all subjects under the NFNC test (see figure \@ref(fig:figs)). Moreover, this increase reached statistical significance (p-value = 0.015) - ready to publish! Looking at the plot I was pondered about the "outlying" patient (red dot). His/her Tlim increased by a whooping 400 seconds! This is huge compared to the other patients. Then I wondered how would the results change if we excluded him/her from the analysis? And here is where the problems start. 

There is no way from the text to figure out which test was used to produce the p-value of 0.015. Is is a paired t-test or a Wilcoxon test? (they mention both in the statistical analysis section.). So it is impossible to evaluate and/or try to reproduce the results. 

Having abandoned the idea of being able to reproduce the analysis I started thinking about reporting guidelines, hence the title of this post. I thought the journal must have guidelines for reporting statistical analysis. No, it does not and unfortunately, most of the biomedical journals don't have statistical reporting guidelines even though 40 years ago O'Fallon and colleges recommended that "Standards governing the content and format of statistical aspects should be developed to guide authors in the preparation of manuscripts" [@o1978should]. Since then many repeated the message. A few sporadic attempts are usually editorials such as @cummings2003reporting, @curran2004guidelines and @arifin2016reporting. 

Recently, @lang2013basic published a comprehensive set of statistical reporting guidelines suitable for medical journals - the SAMPL guidelines. "The SAMPL guidelines are designed to be included in a journal’s Instructions for Authors”. So they journals just need to refer to them! As there are many general reporting guidelines based on the study design as such CONSORT, STROBE, PRISMA etc (see http://www.equator-network.org/) that authors in many journals must adhere to, I believe the SAMPL guidelines is a big step forward on reporting statistics. The only journal (that I know of) that suggests the use of the SAMPL guidelines is the British Journal of Dermatology [@hollestein2015guidelines]. (I'll keep adding to this list). 

Now that the guidelines exist, let's make use of them. 


# References