---
title: "Klingons on the starboard bow?"
author: Me
date: '`r format(Sys.Date(), "%d. %b %Y")`'
slug: significance
categories: [puzzle]
tags: [puzzle]
subtitle: ''
summary: "Puzzle solution"
authors: []
lastmod: '2025-01-17T14:27:06Z'
featured: no
image:
  caption: 'created by DALL·E'
  focal_point: ''
  preview_only: no
projects: []
draft: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The puzzle [Klingons on the starboard bow?](https://academic.oup.com/jrssig/article/21/4/4/7730926) is

> “Captain, there is an alien ship approaching on the starboard bow,” said Chekhov.

> “What kind of vessel is it?” enquired James T. Kirk, commander of the Starship Enterprise.

> “A Klingon vessel, captain, I think,” said the ensign.

> “Analysis, Mr Spock,” said the commander to his first officer.

> “It could well be a Klingon vessel, captain, 90 per cent of ships in this sector are Klingon.”

> “And the other 10 per cent are Romulan vessels?”

> “Precisely, captain.”

> “Well, Spock, as you know, we are at war with the Klingons and have recently signed a peace treaty with the Romulans. I am wary of firing a photon torpedo after the debacle of the M5 computer.* Starfleet are insisting that we be 95 per cent confident a ship is of Klingon origin before we fire on it. How good is ensign Chekhov at identifying Klingon vessels?”

> “His records show that the probability he says it’s a Klingon ship when it is a Klingon ship is 98 per cent and …”

> “That’s all the evidence we need,” interrupted the captain. “Fire the photon torpedoes.”

> Has Captain Kirk made the right decision or should Spock step in and voice his concern?

## Solution
To determine if Captain Kirk made the right decision we need to calculate the probability that the ship is indeed Klingon, given Chekhov's identification capabilities. 

Let’s denote this probability, $\text{P(K given C)}$: the probability that the ship is Klingon ($\text{K}$) given Chekhov says it is Klingon ($\text{C}$).

From the dialogue we know:

- $\text{P(K)=0.9}$: 90% of ships in this sector are Klingon.
- $\text{P(R)=0.1}$: 10% of ships in this sector are Romulan.
- $\text{P(C given K)=0.98}$: If the ship is Klingon, Chekhov correctly identifies it as Klingon 98% of the time.

We apply [Bayes’ theorem](https://www.investopedia.com/terms/b/bayes-theorem.asp): 

$$\text{P(K given C)} = \frac{\text{P(C given K)⋅P(K)}}{\text{P(C given R)⋅P(R) + P(C given K)⋅P(K)}}$$

Bayes’ theorem gives the probability of an event (here $\text{P(K given C))}$ based on new information that is related to that event. In our case, we know that 10\% of ships in this sector are Klingon ($\text{P(K)}$) and we want to know how this is changed/updated based on Chekhov’s performance in identifying Klingon ships, $\text{P(C given K)}$.  

The only unknown is on the right-hand side, $\text{P(C given R)}$. This is the probability Chekhov misidentifies a Romulan ship as Klingon. 

Without this information, we cannot calculate the exact probability. However, we can determine the maximum value of $\text{P(C given R)}$ that would still meet Starfleet's 95% confidence requirement.

That is, we want $\text{P(K given C) > 0.95}$.

Solving the inequality we end up with $\text{P(C given R) < 0.46}$.

This means that if Chekhov misidentifies Romulan ships as Klingon less than 46% of the time, the confidence level would be above 95%, meeting Starfleet's requirement. 

Given Chekhov's high accuracy with Klingon ships (98%), it's unlikely his error rate for Romulan ships would be as high as 46%. In fact, this is worse than a random guess! Therefore, it's probable that the actual confidence level is above 95%.

Captain Kirk is right to fire the torpedoes because he knows that Chekhov would be able to recognise Romulan ships at least 46% of the time! 

